repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-symlinks
      - id: pretty-format-json
        args: ["--autofix"]
      - id: fix-byte-order-marker
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args:
          ["--with", "dev", "-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.4.4
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt"]
        files: ^poetry.lock$
  - repo: https://github.com/haatveit/remove-if-present
    rev: v0.1.0
    hooks:
      - id: remove-if-present
        args: ["requirements.txt"]
